services:
  redis-1:
    container_name: redis-1
    image: redis:7-alpine
    volumes:
      - ./conf/redis-1.conf:/redis/redis.conf:ro
      - ./data/redis-1:/data:rw
    entrypoint:
      - redis-server
      - /redis/redis.conf
    ports:
      - 7001:7001
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: "100M"
  redis-2:
    container_name: redis-2
    image: redis:7-alpine
    volumes:
      - ./conf/redis-2.conf:/redis/redis.conf:ro
      - ./data/redis-2:/data:rw
    entrypoint:
      - redis-server
      - /redis/redis.conf
    ports:
      - 7002:7002
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: "100M"
  redis-3:
    container_name: redis-3
    image: redis:7-alpine
    volumes:
      - ./conf/redis-3.conf:/redis/redis.conf:ro
      - ./data/redis-3:/data:rw
    entrypoint:
      - redis-server
      - /redis/redis.conf
    ports:
      - 7003:7003
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: "100M"
  redis-4:
    container_name: redis-4
    image: redis:7-alpine
    volumes:
      - ./conf/redis-4.conf:/redis/redis.conf:ro
      - ./data/redis-4:/data:rw
    entrypoint:
      - redis-server
      - /redis/redis.conf
    ports:
      - 7004:7004
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: "100M"
  redis-5:
    container_name: redis-5
    image: redis:7-alpine
    volumes:
      - ./conf/redis-5.conf:/redis/redis.conf:ro
      - ./data/redis-5:/data:rw
    entrypoint:
      - redis-server
      - /redis/redis.conf
    ports:
      - 7005:7005
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: "100M"
  redis-6:
    container_name: redis-6
    image: redis:7-alpine
    volumes:
      - ./conf/redis-6.conf:/redis/redis.conf:ro
      - ./data/redis-6:/data:rw
    entrypoint:
      - redis-server
      - /redis/redis.conf
    ports:
      - 7006:7006
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: "100M"
  redis-init:
    container_name: redis-init
    image: redis:7-alpine
    volumes:
      - ./conf/init.sh:/init.sh:ro
    entrypoint:
      - /init.sh
    deploy:
      resources:
        limits:
          cpus: 0.1
          memory: "50M"
