services:
  pg:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-P@ssw0rd}
      PGDATA: /data/postgres
    volumes:
       - ./data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
